version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    env_file:
      - mongo.env
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 0.3

volumes:
  mongo-data:
